export { default as HomePage } from './HomePage.vue'
export { default as DonatePage } from './DonatePage.vue'
export { default as NewsPage } from './NewsPage.vue'
export { default as StatisticPage } from './StatisticPage.vue'
export { default as SettingsPage } from './SettingsPage.vue'
export { default as NotFoundPage } from './NotFoundPage.vue'
